[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "tradepy"
version = "0.0.1"
description = ""
authors = []
license = { text = "MIT" }
readme = "README.md"
dependencies = [
    "pandas>=2.2.3",
    "yfinance>=0.2.52"
]
